# SPDX-FileCopyrightText: 2026 OpenBasil Contributors
#
# SPDX-License-Identifier: Apache-2.0

[workspace]

[package]
name = "basil-artifact-signing"
version = "0.1.0"
authors = ["info@openbasil.org"]
edition = "2024"
homepage = "https://github.com/openbasil/basil"
license = "Apache-2.0"
publish = false
repository = "https://github.com/openbasil/basil"

[[bin]]
name = "artifact-signing"
path = "src/main.rs"

[dependencies]
basil = { path = "../../crates/basil-client" }

anyhow = "1"
ed25519-dalek = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.14.6"
